### ISSUE TITLE
CBM: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by jagdeeppani** [cheng-li/pyramid#4]
When I run CBM with 10K training samples, 10K features and 12 labels (70 label sets) , it works fine. But when I increase the number of training samples to 150K, it throws the following error.. Most of the features are real valued. The dataset is around 95% sparse. The code uses around 50GB memory out of 128GB.

_Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at edu.neu.ccs.pyramid.application.AppLauncher.invokeMain(AppLauncher.java:72)
        at edu.neu.ccs.pyramid.application.AppLauncher.launch(AppLauncher.java:39)
        at edu.neu.ccs.pyramid.application.AppLauncher.main(AppLauncher.java:24)
**Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded**
        at java.lang.String.split(String.java:2338)
        at java.lang.String.split(String.java:2410)
        at edu.neu.ccs.pyramid.dataset.TRECFormat.fillMultiLabelClfDataSet(TRECFormat.java:332)
        at edu.neu.ccs.pyramid.dataset.TRECFormat.loadMultiLabelClfDataSet(TRECFormat.java:159)
        at edu.neu.ccs.pyramid.dataset.TRECFormat.loadMultiLabelClfDataSet(TRECFormat.java:106)
        at edu.neu.ccs.pyramid.application.App5.train(App5.java:58)
        at edu.neu.ccs.pyramid.application.App5.main(App5.java:38)
        ... 7 more_

From web, what I got to know is, this error is raised when most of the run time is consumed in Garbage collection and the progress become too slow. Java shows this error as it suspects the program may never finish. As per the paper, CBM is able to handle TMC2007 dataset which is relatively large. So I am hoping there is a solution to this issue.

**Any idea how to fix this issue?**

**Comment by cheng-li** [comment]
Hi @jagdeeppani 

In the properties file, there is an option "input.matrixType". It is set to "dense" by default. If your dataset contains a large number of sparse features, it is better to use some sort of sparse format. Specifically, if CBM uses logistic regression learners (that is, mixture.multiClassClassifierType=lr, mixture.binaryClassifierType=lr), you can set "input.matrixType=sparse_sequential", and if CBM uses boosting learners (that is, mixture.multiClassClassifierType=boost, mixture.binaryClassifierType=boost), you can set "input.matrixType=sparse_random". Hopefully this will reduce memory usage significantly and make it work.

**Comment by jagdeeppani** [comment]
Thanks for the reply.
In the properties file, I am already using "input.matrixType=sparse_random", "mixture.multiClassClassifierType=boost" and "mixture.binaryClassifierType=boost".

**Comment by jagdeeppani** [comment]
I have independent doubts here: 

- Is it important for the features to be in a sequential order? e.g. for a multi-label dataset, Is it fine to input "0,2 0:0.64 3:0.66 1:0.685" or should the input be "0,2 0:0.64 1:0.685 3:0.66" ?
- For 10K samples, 10K features and 12 labels: It took around 13 hours to complete 10 iterations along with the initialization. This is on a standard ubuntu machine of 16GB RAM, i5, 3.3Ghz. _Is this normal?_

Thanks in advance.

**Comment by cheng-li** [comment]
So if I understood your description correctly, you ran CBM on two different machines, one with 16G RAM and the other with 128 RAM. You were able to get the 10K samples data to work on the small machine (although taking a long time) but couldn't get the 150k samples data to work on the big machine. Is that correct? On the big machine, did you set your max heap size to 50G or 128G? From the exception message, it looks like the training had not started yet. It crashed when loading the data, which seems somewhat unusual. Because we were able to load bigger datasets with less than 50 RAM. Could you please provide more information about you set your JVM (e.g. the -Xmx value in the pyramid lunching script)? Also, are you using the latest version of the code (v0.7.1)? We had a memory issue before and it has been fixed in the latest version.

Regarding the data format: the order does not matter since you provide feature indices.

Regarding the speed: we honestly haven't tried our code on a standard Ubuntu machine like the one you described. We are using a computing cluster with each machine having Intel Xeon CPU E5-2690 v3 2.6GHz, 48 logical cores and 128GB of RAM. On TMC dataset with 29K instances and 49K features, it took us about 40 minutes to train CBM+LR with 40 components. You can find more timing results here http://www.chengli.io/publications/li2016conditional_supplementary.pdf. For boosting learners, our experience is that the training usually takes more time compared with logistic regression learners. Also, if your data is high dimensional sparse data, e.g., bag of words features for text data, logistic regression learners will usually achieve higher accuracy than boosting learners. So we recommend you also try LR learners and see whether that's faster and more accurate. Our implementation performs multi-threading on a single machine. So if you double the number of cores, it would roughly halve your training time. Also, running the code with insufficient RAM may slow down the training. Would be curious to know whether it runs faster on your bigger machine.

**Comment by jagdeeppani** [comment]
Yes you are right. Currently I am facing the "out of memory error" when I run CBM with 150K samples on the big machine (128G). The current heap size is 26G. I will change it to around 60G and will try again. I will keep you informed about the outputs.  
Yes, I am using Pyramid v0.7.1 . 

Regarding the speed: As per your suggestion I tried to run CBM with LR on 150K samples, it failed showing "java.lang.RuntimeException: value is infinite". Please see the attached log. I am getting the same error when running with 10K samples too.

Log:  [cbmLog_LR.txt](https://github.com/cheng-li/pyramid/files/526542/cbmLog_LR.txt)

**Comment by cheng-li** [comment]
I just tried CBM+LR on a few datasets but couldn't reproduce the "java.lang.RuntimeException: value is infinite" exception you had. Looks like there might be something special with your data. If you don't mind, can you please share with us your dataset so that we can identify the issue? If the whole dataset is very big, you can probably just share a subset (assuming we can reproduce this error on the subset).

BTW, we just released v0.7.3 with a few enhancements.

**Comment by jagdeeppani** [comment]
Thanks for your comments.

**Memory overflow error:** 
By extending the max heap-size to 50 GB, I am able to load the dataset (152K samples, 10K features).

**CBM +LR "value is infinite exception":**
Unfortunately, I can't share the data as it is private in nature. I ran CBM+LR on the "scene" data and it worked fine. So, currently I am thoroughly verifying our dataset and its formatting. I will keep you informed when I find a way out. At present I am using v0.7.3.

**Comment by cheng-li** [comment]
Hi @jagdeeppani 

We managed to reproduce the "value is infinite exception" on one of our datasets. It was caused by a numerical stability issue during some KL divergence computation. We switched to a more stable way of computing KL divergence and fixed that problem. We have released a [new version](https://github.com/cheng-li/pyramid/releases/tag/v0.7.4) with the fix. Thank you for reporting this issue!

**Comment by jagdeeppani** [comment]
Thanks a bunch cheng-li. 
Now I am using the new version and it is running fine. 
Just for a note, I see CBM+LR is quite faster (at least 6 times) than CBM+boost with the default set of parameters, but in terms of performance CBM+boost is quite better. 
Thank you again for the new version.

**Comment by cheng-li** [comment]
Interesting. I guess for CBM+LR you may need to tune the variance parameter a little bit to reach the best performance while CBM+boost is less sensitive to hyper parameters.

**Comment by jagdeeppani** [comment]
I am also hoping that by tuning CBM+LR performance may improve. :-)
thanks.
